{
 "title": "Torrent Trackers Stats",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Host",
    "query": {
     "query": "label_values(tracker_ratio,instance)"
    }
   },
   {
    "name": "tracker",
    "label": "Tracker",
    "query": {
     "query": "label_values(tracker_ratio,tracker)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current Ratio",
   "type": "stat",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "upload_bytes{instance=~\"$hostname.+\", tracker=~\"$tracker\"} / on(tracker) download_bytes{instance=~\"$hostname.+\", tracker=~\"$tracker\"}",
     "legendFormat": "{{tracker}}"
    }
   ]
  },
  {
   "title": "Ratio over time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "upload_bytes{instance=~\"$hostname.+\",  tracker=~\"$tracker\"} / on(tracker) download_bytes{instance=~\"$hostname.+\",  tracker=~\"$tracker\"}",
     "legendFormat": "{{tracker}}"
    }
   ]
  },
  {
   "title": "Total Uploaded",
   "type": "stat",
   "gridPos": { "h": 3, "w": 14, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(upload_bytes{instance=~\"$hostname.+\", tracker=~\"$tracker\"}[$__range])",
     "legendFormat": "{{tracker}}"
    }
   ]
  },
  {
   "title": "Bonus Points",
   "type": "stat",
   "gridPos": { "h": 2, "w": 14, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bonus_points{instance=~\"$hostname.+\", tracker=~\"$tracker\"}",
     "legendFormat": "{{tracker}}"
    }
   ]
  },
  {
   "title": "Download",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "download_bytes{instance=~\"$hostname.+\",  tracker=~\"$tracker\"}",
     "legendFormat": "{{tracker}}"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "upload_bytes{instance=~\"$hostname.+\",  tracker=~\"$tracker\"}",
     "legendFormat": "{{tracker}}"
    }
   ]
  }
 ]
}